config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#home'
  resources :users
  resources :aboutus
  resources :services
  resources :contactus
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true, length: {minimum: 5}
    validates :name, presence: true, length: {minimum: 5}
    validates :phonenumber, presence: true, length: {minimum: 5}
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def home
        render json: "hello"
    end
end

app/controllers/contactus_controller.rb
class ContactusController < ApplicationController
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def home
    end

    def show
        @user = User.find(params[:id])
    end
    
    def index
        @user = User.all
    end

    def new
    
    end

    def create
        @user = User.new(params.require(:user).permit(:email, :name, :phonenumber, :description))
        @user.save
        redirect_to :root
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/aboutus/index.html.erb
<header class="header">
    <div class="container">
        <div class="navbar">
                <%= link_to 'Company LOGO', root_path, {:class => "a companylogo"} %>
            <nav>
            <ul class="navul">
                <li class="link">
                    <%= link_to 'Home', root_path, {:class => "a"} %>
                </li>
                <li class="link">
                    <%= link_to 'About Us', aboutus_path, {:class => "a"} %>
                </li>
                <li class="link">
                    <%= link_to 'Services', services_path, {:class => "a"} %>
                </li>
                <li class="link">
                    <button class="contactus a" id="contactus">
                        Contact Us
                    </button>
                </li>
            </ul>
            </nav>
        </div>
    </div>
</header>

    <h2 class="welcomeheader aboutUsHeader">About Us</h2>
    <div class="aboutusbackground"> 
        <div class="bodycontainer">
            <div class="bodylorem">
                
                <h3 class="welcomeheadertwo">Website Design & Development </h3>
                    <p class="aboutUsParagraph">
                        Aloe Design Co. is a start to finish web design company catered to all your web needs. Here at Aloe our goal is to help make your web goals a reality, whether that is helping you take the first steps to taking your business online, refurbishing that old design scheme, or start to finish web design implementation and deployment and much more. We have a team that can help all your needs, worries and questions from beginning to end, we started out as a small business and our goal is to give that same small business and personable feel that got us to where we are today! Please reach out if you have any questions or would like a free consultation to see if you're ready to take the first or final step into making your web plans a reality.
                    </p>
                    </br>
                    
            </div>
            <div class= "welcomeimage aboutusimage">
                <%= image_tag('founders.png') %>
            </div> 
        </div>
        </div>

        <div class="footer">
            <p>Footer</p>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MakeShift</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Tammudu+2:wght@600&family=Lato&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Tammudu+2:wght@600&family=Lato:wght@400;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Tammudu+2:wght@600&family=Lato:wght@400;900&family=Oswald&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap" rel="stylesheet">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="bg-modal">
      <div class="modal-content">
        <div id="formbox">
          <div class="close-button">+</div>
          <h1 class="modalTitle">Contact Us</h1>
          <%= form_with scope: :user, url: users_path, local: true do |f| %>
              <p>
                <div class="modal-form-content">
                    <div class="formstuff">
                        <%= f.text_field :name, class: "formTextField" %></br>
                        <%= f.label :name, class: "formLabel" %></br>
                    </div>

                    <div class="formstuff">
                        <%= f.text_field :email, class: "formTextField" %></br>
                        <%= f.label :email, class: "formLabel" %></br>
                    </div>
            
                    <div class="formstuff">
                        <%= f.text_area :phonenumber, class: "formTextField" %></br>
                        <%= f.label :Description, class: "formLabel" %></br>
                    </div>
            
                    <div>
                        <%= f.submit class: "button modalButton", value: "Submit" %>
                    </div>
                </div>
              </p>
          <% end %>
      </div>
          </div>
    </div>
    <%= yield %>
    <script>
      document.getElementById('contactus').addEventListener('click', 
        function() {
          document.querySelector('.bg-modal').style.display = 'flex';
      });

      document.querySelector('.close-button').addEventListener('click',
      function(){
            document.querySelector('.bg-modal').style.display = 'none';
      });
  </script>

  </body>
</html>

app/views/services/index.html.erb
<header class="header">
    <div class="container">
        <div class="navbar">
                <%= link_to 'Company LOGO', root_path, {:class => "a companylogo"} %>
            <nav>
            <ul class="navul">
                <li class="link">
                    <%= link_to 'Home', root_path, {:class => "a"} %>
                </li>
                <li class="link">
                    <%= link_to 'About Us', aboutus_path, {:class => "a"} %>
                </li>
                <li class="link">
                    <%= link_to 'Services', services_path, {:class => "a"} %>
                </li>
                <li class="link">
                    <button class="contactus a" id="contactus">
                        Contact Us
                    </button>
                </li>
            </ul>
            </nav>
        </div>
    </div>
</header>
<body>
<div class="jumbotron">
        <%= image_tag('header.png') %>
</div>

 <div class="servicepage">
        <h2 class="welcomeheader">Our Services</h2>
        <h3 class="welcomeheadertwo">Website Design & Development </h3>
            <p> Our process for all services begins with a complimentary 40-minute consultation and a questionnaire where we will learn more about you and your business needs are, and answer any questions that you might have.</p>
            <br>
            <p> The possibilities are endless.</p>
</div>
<div class="buttoncontainer">
    <button class="button">Free Consultation</button>
</div>
<div class="wrapper">
    <div class="box1">
        <%= image_tag('logodesign_icon.png', :class => "serviceslogodesignimg") %>
        <h3 class="servicepage_header"> Logo Design</h3>
        <p class="servicepage_description">
        We will take the time to really understand what message you would like to send and create a meaningful logo for your business.
        </p>
        <ul>
            <li class="servicesarrowfont">Primary Logo</li>
            <li class="servicesarrowfont">Secondary Logo</li>
            <li class="servicesarrowfont">Alternative Logo Options </li>
            <li class="servicesarrowfont">Alternative Logo Options </li>
            <li class="servicesarrowfont">Creative Direction </li>
            <li class="servicesarrowfont">User Prefrance Testing </li>
        </ul>
    </div>
    <div class="box2">
        <%= image_tag('webdesign_icon.png', :class => "serviceslogodesignimg") %>
        <h3 class="servicepage_header"> Web Design & Development</h3>
        <p class="servicepage_description">
        From concept to development our team will deliver a beautiful responsive website to help your business thrive.
        </p>
        <ul>
            <li class="servicesarrowfont">Low Fidelty Wireframes(Designs) and Iterations</li>
            <li class="servicesarrowfont">High Fidelty Wireframes(Designs) and Iterations</li>
            <li class="servicesarrowfont">Fully Responsive and Deployed Website</li>
            <li class="servicesarrowfont">Creative Direction</li>
        </ul>    
    </div>
    <div class="box3">
        <%= image_tag('seo_icon.png', :class => "serviceslogodesignimg") %>
        <h3 class="servicepage_header"> Search Engine Optimization</h3>
        <p class="servicepage_description">
        We ensure that your clients are able to find your company with little effort in order to help make your business successful. 
        </p>
        <ul>
            <li class="servicesarrowfont">Specialize Content</li>
            <li class="servicesarrowfont">Quality Domains</li>
            <li class="servicesarrowfont">Website and Server Optimizations</li>
        </ul> 
    </div>
        <div class="box4">
        <%= image_tag('websitemaintenance_icon.png', :class => "serviceslogodesignimg") %>
        <h3 class="servicepage_header">Website Maintenance</h3>
        <p class="servicepage_description">
        Our team is available for any website maintenance you may came across. We are here to make your life easier.
        </p>
        <ul>
            <li class="servicesarrowfont">Content Updates</li>
            <li class="servicesarrowfont">Creative Directtion</li>
            <li class="servicesarrowfont">Alternative Options</li>
        </ul>
    </div>
    <div class="box5">
        <%= image_tag('contentdevelopment_icon.png', :class => "serviceslogodesignimg") %>
        <h3 class="servicepage_header">Content Development</h3>
        <p class="servicepage_description">
        We have proffesional writers that will ensure the message your business wants to comminicate is relayed to your clients.
        </p>
        <ul>
            <li class="servicesarrowfont">Specialized Content</li>
            <li class="servicesarrowfont">User Centered Content and Engagment</li>
            <li class="servicesarrowfont">Editing</li>
            <li class="servicesarrowfont">Creative Direction</li>
        </ul>
    </div>
    <div class="box3">
        <%= image_tag('branding_icon.png', :class => "serviceslogodesignimg") %>
        <h3 class="servicepage_header">Branding</h3>
        <p class="servicepage_description">
        We provide creative consulting and direction to help create a meaningful brand for your business. Things incuded in this service include: 
        </p>
        <ul>
            <li class="servicesarrowfont">Color Pallet</li>
            <li class="servicesarrowfont">Typography Set</li>
            <li class="servicesarrowfont">Style Guide</li>
            <li class="servicesarrowfont">Mood Board</li>
        </ul>
    </div>
</div>
        <div class="footer">
            <p>Footer</p>
        </div>

app/views/users/home.html.erb
<header class="header">
    <div class="container">
        <div class="navbar">
                <%= link_to 'Company LOGO', root_path, {:class => "a companylogo"} %>
            <nav>
            <ul class="navul">
                <li class="link">
                    <%= link_to 'Home', root_path, {:class => "a"} %>
                </li>
                <li class="link">
                    <%= link_to 'About Us', aboutus_path, {:class => "a"} %>
                </li>
                <li class="link">
                    <%= link_to 'Services', services_path, {:class => "a"} %>
                </li>
                <li class="link">
                    <button class="contactus a" id="contactus">
                        Contact Us
                    </button>
                </li>
            </ul>
            </nav>
        </div>
    </div>
</header>
<body>
        <div class="jumbotron">
                <%= image_tag('header.png', :class => "imagess") %>
        </div>
        <div class="bodycontainer">
            <div class= "welcomeimage firstimage">
                <%= image_tag('firstimage.jpg') %>
            </div>
        
            <div class="bodylorem">
                <h2 class="welcomeheader">Let Us Simplify Your Business</h2>
                <h3 class="welcomeheadertwo">Website Design & Development </h3>
                <p> Aloe Design Co. is a creative business located in beauitful Denver, Colorado working with clients nation wide.</p>
                <br>
                <p> We provide high quality web design and development, brand identity, and creative direction for entrepreneurs and small businesses. The possibilites are endless on how we can help your business thrive.</p>
                <br>
                <p> We are here to help you bring your vision to life through creative direction and development.</p>
            </div>
        </div>
        <div class="buttoncontainer">
        <button class="button">Free Consultation</button>
        </div>



        <div class="servicesbackground">
            <h2 class="serviceheader">Our Services</h2>
            <div class="servicescontainer">
                <div class="service" id="firstservice">
                    <%= image_tag('branding_icon.png', :class => "responsiveimg") %>
                    <h3 class="servicehead">
                        Branding
                    </h3>
                    <p class="servicedescription">
                    We provide creative consulting and direction to help create a meaningful brand for your business.
                    </p>
                </div>
                <div class="service">
                    <%= image_tag('webdesign_icon.png', :class => "responsiveimg")  %>
                    <h3 class="servicehead">
                        Web Design & Development
                    </h3>
                    <p class="servicedescription">
                    From concept to development our team will deliver a beutiful responsive website to help your business thrive.
                    </p>
                </div>
                <div class="service">
                    <%= image_tag('logodesign_icon.png', :class => "responsiveimg")  %>
                    <h3 class="servicehead">
                        Logo Design
                    </h3>
                    <p class="servicedescription">
                    We will take the time to really understand what message you would like to send and create a meaningful logo for your business.
                    </p>
                </div>
            </div>
            <div class="servicescontainer">
                <div class="service">
                    <%= image_tag('seo_icon.png', :class => "responsiveimg")  %>
                    <h3 class="servicehead">
                        SEO
                    </h3>
                    <p class="servicedescription">
                    We ensure that your clients are able to find your company with little effort in order to help make your business successful. 
                    </p>
                </div>
                <div class="service">
                    <%= image_tag('contentdevelopment_icon.png', :class => "responsiveimg")  %>
                    <h3 class="servicehead">
                        Content Development
                    </h3>
                    <p class="servicedescription">
                    We have proffesional writers that will ensure the message your business wants to comminicate is relayed to your clients.
                    </p>
                </div>
                <div class="service" id="finalservice">
                    <%= image_tag('websitemaintenance_icon.png', :class => "responsiveimg")  %>
                    <h3 class="servicehead">
                        Website Maintenance
                    </h3>
                    <p class="servicedescription">
                    Our team is available for any website maintenance you may came across. We are here to make your life easier.
                    </p>
                </div>
            </div>
            <div class="buttoncontainer">
            <button class="button">Learn More</button>
            </div>
        </div>
        


        <div class="bodycontainer">
            <div class="bodylorem">
                <h2 class="welcomeheader">Meet the founders!</h2>
                <h3 class="welcomeheadertwo">Website Design & Development </h3>
                    <p> Aloe Design Co. was founded by a couple in Denver, Colorado who believes that entreponours and small business are what keep our economy going. As a is a fellow small business, we have worked hard to brand ourselves as a company that you as a business owner can trust with your web design needs.</p>
                    <br>
                    <p>We pride ourselves on providing great communication, high quality deliverables, and cost effective services. We love what we do and cant wait to meet you and turn your vision into a reality. </p>
            </div>
            <div class= "welcomeimage foundersimage">
                <%= image_tag('founders.png') %>
            </div> 
        </div>


        <div class="servicesbackground">
        <div class="bodycontainer">
            <div class= "welcomeimage">
                <%= image_tag('consult_photo.jpg', :class => "consultimage" )%>
            </div> 
            <div class="bodylorem" id="formbox">
                <h1 class="formTitle">Free Consultation</h1>
                <%= form_with scope: :user, url: users_path, local: true do |f| %>
                    <p>
                        <div class="formstuff">
                            <%= f.text_field :name, class: "formTextField" %></br>
                            <%= f.label :name, class: "formLabel" %></br>
                        </div>

                        <div class="formstuff">
                            <%= f.text_field :email, class: "formTextField" %></br>
                            <%= f.label :email, class: "formLabel" %></br>
                        </div>
                
                        <div class="formstuff">
                            <%= f.text_field :phonenumber, class: "formTextField" %></br>
                            <%= f.label :phonenumber, class: "formLabel" %></br>
                        </div>
                
                        <div>
                            <%= f.submit class: "button formButton", value: "Submit" %>
                        </div>
                
                    </p>
                <% end %>
            </div>
        </div>
        <div class="footer">
            <p>Footer</p>
        </div>

</body>

app/views/users/index.html.erb
<h1>Lets party<h1>
<p> <% @user.each do |user|%>
    <h1><%= user.name %></h1>
    <h1><%= user.email %></h1>
    <h1><%= user.phonenumber %></h1></br>
    <% end %>
 </p>